services:
  - type: web
    name: cpt-campaign-reporter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000 --workers 1 --threads 8 --timeout 600
    envVars:
      - key: YOUTUBE_API_KEY
        value: AIzaSyCvfUzTHKJ2m6M6BIMvOrNJeCncaPUlJs8
      - key: REBRANDLY_API_KEY
        value: bf6e85cdd43f4ad68579059ee3dc5882
      - key: TWITCH_CLIENT_ID
        value: sd19zv0wcjyeq4div4qv3unyev4tuh
      - key: TWITCH_SECRET
        value: uaol2jp7pyjlm3bnurma12dhzrcl06
